const fs = require('fs');
const { exec } = require('child_process');

console.clear();
console.log("Reading 'paste-connection-string-here.txt'...");

try {
    const content = fs.readFileSync('paste-connection-string-here.txt', 'utf8');
    const lines = content.split('\n');
    
    let connString = '';
    let password = '';
    let currentSection = 0;

    for (let line of lines) {
        line = line.trim();
        if (!line) continue;
        if (line.includes('---')) continue;
        if (line.includes('STEP 1')) { currentSection = 1; continue; }
        if (line.includes('STEP 2')) { currentSection = 2; continue; }
        if (line.startsWith('(')) continue; // Skip instructions

        if (currentSection === 1 && line.startsWith('postgresql://')) {
            connString = line;
        } else if (currentSection === 2 && line.length > 0) {
            password = line;
        }
    }

    if (!connString) {
        throw new Error("Could not find the Connection String (starting with postgresql://) in STEP 1.");
    }
    if (!password) {
        throw new Error("Could not find the Password in STEP 2.");
    }

    // Combine them safely
    // IMPORTANT: URL encode the password to handle special characters like @, #, etc.
    const encodedPassword = encodeURIComponent(password);
    
    let finalUrl = connString;
    if (finalUrl.includes('[YOUR-PASSWORD]')) {
        finalUrl = finalUrl.replace('[YOUR-PASSWORD]', encodedPassword);
    } else {
        // Fallback: If they pasted a URL that already has a password, we might warn them
        // But for now, let's assume if they provided a password in Step 2, they want to use it.
        // We can't easily parse every postgres URL structure safely without a library, 
        // but Supabase URLs are consistent.
        console.log("ℹ️  Note: Your connection string didn't have the [YOUR-PASSWORD] placeholder.");
        console.log("   I will assume the password in the URL is correct, or try to inject the new one if it looks like a placeholder.");
    }

    // Generate Direct URL
    let directUrl = finalUrl;
    if (directUrl.includes('6543')) {
        directUrl = directUrl.replace('6543', '5432');
    }
    if (directUrl.includes('pooler.supabase.com')) {
        directUrl = directUrl.replace('pooler.supabase.com', 'supabase.co');
    }

    const authSecret = require('crypto').randomBytes(32).toString('base64');

    const envContent = `# Auto-generated by finalize-setup.js
DATABASE_URL="${finalUrl}"
DIRECT_URL="${directUrl}"

# NextAuth
NEXTAUTH_SECRET="${authSecret}"
NEXTAUTH_URL="http://localhost:3000"
`;

    fs.writeFileSync('.env', envContent);
    console.log("✅ .env file updated successfully.");

    console.log("🚀 Syncing database with Supabase...");
    
    const command = 'powershell -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass; npx prisma db push"';
    const child = exec(command);

    child.stdout.on('data', (data) => console.log(data.toString()));
    child.stderr.on('data', (data) => console.error(data.toString()));

} catch (err) {
    console.error("\n❌ ERROR: " + err.message);
    console.error("Please check 'paste-connection-string-here.txt' and try again.");
}
