const { execSync } = require('child_process');
const fs = require('fs');
const crypto = require('crypto');

const projectRef = 'vbgvcaqxbdtwozacwvhl';
const password = '123456?Kapilla/';
const encodedPassword = encodeURIComponent(password);

// Common Supabase Pooler Hosts (IPv4 compatible)
const regions = [
    'aws-0-af-south-1.pooler.supabase.com',   // Cape Town (Likely for Tanzania)
    'aws-0-eu-north-1.pooler.supabase.com',   // Stockholm
    'aws-0-me-central-1.pooler.supabase.com', // UAE
    // 'aws-0-eu-central-1.pooler.supabase.com', // Checked: Fail
    // 'aws-0-us-east-1.pooler.supabase.com',    // Checked: Fail
    // 'aws-0-eu-west-1.pooler.supabase.com',    // Checked: Fail
    // 'aws-0-eu-west-2.pooler.supabase.com',    // Checked: Fail
    // 'aws-0-ap-south-1.pooler.supabase.com',   // Checked: Fail
    'aws-0-sa-east-1.pooler.supabase.com',    // Sao Paulo
    'aws-0-ap-southeast-1.pooler.supabase.com', // Singapore
    'aws-0-ap-southeast-1.pooler.supabase.com', // Singapore
    'aws-0-us-west-1.pooler.supabase.com',
    'aws-0-us-west-2.pooler.supabase.com',
    'aws-0-eu-west-3.pooler.supabase.com',    // Paris
    'aws-0-ca-central-1.pooler.supabase.com'
];

console.log("\x1b[36m%s\x1b[0m", "========================================");
console.log("\x1b[36m%s\x1b[0m", "   AUTO-FIXING DATABASE CONNECTION      ");
console.log("\x1b[36m%s\x1b[0m", "========================================");
console.log("I detected an IPv6 issue. I am now scanning for a valid IPv4 connection...");

let success = false;

for (const host of regions) {
    // Construct the Transaction Mode URL (Port 6543)
    const url = `postgresql://postgres.${projectRef}:${encodedPassword}@${host}:6543/postgres`;
    
    // For Direct URL, we can often use the same host on port 5432 with Supavisor, 
    // or just use the pooler URL for both for now to get it working.
    const directUrl = `postgresql://postgres.${projectRef}:${encodedPassword}@${host}:6543/postgres`;

    console.log(`\nTesting connection to: \x1b[33m${host}\x1b[0m ...`);
    
    try {
        // Try to push. If it connects, it will work or give a schema error, not a connection error.
        // We use --skip-generate to speed it up.
        execSync('powershell -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass; npx prisma db push --skip-generate"', {
            env: { ...process.env, DATABASE_URL: url, DIRECT_URL: directUrl },
            stdio: 'pipe' // Hide output, we just care if it throws or not
        });
        
        console.log("\x1b[32m%s\x1b[0m", "✅ CONNECTION SUCCESSFUL!");
        
        // If we get here, it worked!
        const authSecret = crypto.randomBytes(32).toString('base64');
        const envContent = `# Auto-generated by fix-db.js
DATABASE_URL="${url}"
DIRECT_URL="${directUrl}"

# NextAuth
NEXTAUTH_SECRET="${authSecret}"
NEXTAUTH_URL="http://localhost:3000"
`;
        fs.writeFileSync('.env', envContent);
        console.log("✅ .env file updated with the working URL.");
        
        // Run it again to show the user the output
        console.log("\n🚀 Applying database changes...");
        execSync('powershell -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass; npx prisma db push"', {
            env: { ...process.env, DATABASE_URL: url, DIRECT_URL: directUrl },
            stdio: 'inherit'
        });
        
        success = true;
        break; // Stop loop
    } catch (error) {
        const errString = error.message + (error.stderr ? error.stderr.toString() : "") + (error.stdout ? error.stdout.toString() : "");
        if (errString.includes("Tenant or user not found")) {
             console.log("❌ Region mismatch (Tenant not found).");
        } else if (errString.includes("P1001")) {
             console.log("❌ Unreachable (Network/DNS).");
        } else if (errString.includes("P1000")) {
             console.log("❌ Authentication failed (Wrong Password?).");
        } else {
             console.log("❌ Failed: " + errString.substring(0, 50) + "...");
        }

    }
}

if (!success) {
    console.log("\n\x1b[31m%s\x1b[0m", "❌ Could not find a working connection.");
    console.log("Please double-check your password.");
} else {
    console.log("\n\x1b[32m%s\x1b[0m", "🎉 YOU ARE ALL SET! Database is ready.");
}
