const fs = require('fs');
const readline = require('readline');
const { exec } = require('child_process');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.clear();
console.log("\x1b[36m%s\x1b[0m", "===========================================");
console.log("\x1b[36m%s\x1b[0m", "   KAPILLA LOGISTICS - AUTO SETUP WIZARD   ");
console.log("\x1b[36m%s\x1b[0m", "===========================================");
console.log("I will help you configure your database automatically.\n");

console.log("\x1b[33m%s\x1b[0m", "STEP 1: Get your Connection String");
console.log("1. Go to Supabase > Project Settings > Database.");
console.log("2. Look for 'Connection parameters'.");
console.log("3. Copy the URI (Transaction Mode) that looks like:");
console.log("   postgresql://postgres.[REF]:[YOUR-PASSWORD]@aws-0-[REGION].pooler.supabase.com:6543/postgres\n");

rl.question('Paste that Connection String here:\n> ', (rawConnString) => {
  
  console.log("\n\x1b[33m%s\x1b[0m", "STEP 2: Enter your Database Password");
  console.log("(The one you created when you started the project. If you forgot, reset it in Supabase settings.)");
  
  rl.question('Password:\n> ', (password) => {
    
    try {
        let connString = rawConnString.trim();
        password = password.trim();

        // Check if string is empty
        if (!connString || !password) {
            throw new Error("Connection string or password cannot be empty.");
        }

        // SMART REPLACEMENT:
        // 1. If the string has [YOUR-PASSWORD], replace it.
        // 2. If it doesn't, we might need to inject it.
        // Let's assume the standard Supabase format which includes the placeholder.
        let dbUrl = connString.replace('[YOUR-PASSWORD]', password);
        
        // If the user pasted a string that ALREADY had the password (rare but possible),
        // replace won't do anything harmful if the placeholder isn't found, 
        // BUT we need to ensure the final string is valid.
        
        // Auto-generate Direct URL (Session Mode)
        // Logic: Port 6543 -> 5432, pooler.supabase.com -> supabase.co
        let directUrl = dbUrl;
        if (directUrl.includes('6543')) {
            directUrl = directUrl.replace('6543', '5432');
        }
        if (directUrl.includes('pooler.supabase.com')) {
            directUrl = directUrl.replace('pooler.supabase.com', 'supabase.co');
        }

        // Generate Auth Secret
        const authSecret = require('crypto').randomBytes(32).toString('base64');

        const envContent = `# Auto-generated by setup-wizard.js
DATABASE_URL="${dbUrl}"
DIRECT_URL="${directUrl}"

# NextAuth
NEXTAUTH_SECRET="${authSecret}"
NEXTAUTH_URL="http://localhost:3000"
`;

        fs.writeFileSync('.env', envContent);
        console.log("\n\x1b[32m%s\x1b[0m", "✅ Success! Your .env file has been updated.");

        console.log("\n\x1b[33m%s\x1b[0m", "STEP 3: Syncing with Supabase...");
        console.log("Running 'npx prisma db push' for you...");

        // Run the prisma command
        // We use a PowerShell wrapper to bypass execution policy issues
        const command = 'powershell -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass; npx prisma db push"';
        
        const child = exec(command);

        child.stdout.on('data', (data) => {
            console.log(data.toString());
        });

        child.stderr.on('data', (data) => {
            console.error(data.toString());
        });

        child.on('exit', (code) => {
            if (code === 0) {
                console.log("\n\x1b[32m%s\x1b[0m", "🎉 DATABASE SETUP COMPLETE!");
                console.log("You can now deploy to Vercel.");
            } else {
                console.log("\n\x1b[31m%s\x1b[0m", "⚠️  Database sync had some issues. Check the error above.");
            }
            rl.close();
        });

    } catch (err) {
        console.error("\n\x1b[31m%s\x1b[0m", "❌ Error: " + err.message);
        rl.close();
    }
  });
});
